name: lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Upgrade pip
        run: python -m pip install pip --upgrade --user
      - name: Install pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit install
      - name: Install eslint
        run: npm install -D eslint eslint-plugin-vue
      - name: Lint
        run: cd tests && bash lint.sh